### ISSUE TITLE
Question about maximum characters

### ISSUE THREAD

**Issue by mimitantono** [xhongyi/SHD_code#1]
Hi ! I am working on a project for clustering metagenomics DNA sequences, and I would like to use this method before proceed to the expensive sequence alignment. But before that the sequence pairs were already filtered using qgram distance as written on : [Approximate string-matching and the q-gram distance !](http://link.springer.com/chapter/10.1007%2F978-1-4613-9323-8_22)

I was looking at countPassFilter.cc and I got the impression that the method could only handle 128 base pairs. 

Most of the data set that I have consist of sequences with more than 150 base pairs. So when I use the method as following, I found that this method always return true.

```
int length = sequence1->seqlen > sequence2->seqlen ? sequence1->seqlen : sequence2->seqlen;
length = length > 128 ? 128 : length;
char read_t[128] __aligned__; 
char ref_t[128] __aligned__; 
strncpy(read_t, sequence1->seq, length);
strncpy(ref_t, sequence2->seq, length);
bool proceedToAlignment = bit_vec_filter_sse1(read_t, ref_t, length, 1)
```

Could you advise if I have been using it the wrong way?
Thank you in advance!

**Comment by xhongyi** [comment]
Hi,

Thanks for trying out SHD.

What you did seems right.

Can you send me some of the example string pairs that passes q-gram
filtering so I can take a look at them myself?

Also, have you tried replacing q-gram distance with SHD?

In your case, depending on how you implement the q-gram filtering, SHD
might not be very helpful at all...

Thanks,
Hongyi

On Mon, Feb 9, 2015 at 10:47 AM, mimitantono notifications@github.com
wrote:

> Hi ! I am working on a project for clustering metagenomics DNA sequences,
> and I would like to use this method before proceed to the expensive
> sequence alignment. But before that the sequence pairs were already
> filtered using qgram distance as written on : Approximate string-matching
> and the q-gram distance !
> http://link.springer.com/chapter/10.1007%2F978-1-4613-9323-8_22
> 
> I was looking at countPassFilter.cc and I got the impression that the
> method could only handle 128 base pairs. Most of the data set that I have
> consist of sequences with more than 150 base pairs. So when I use the
> method as following, I found that this method always return true.
> 
> int length = sequence1->seqlen > sequence2->seqlen ? sequence1->seqlen : sequence2->seqlen;
> length = length > 128 ? 128 : length;
> char read_t[128] **aligned**;
> char ref_t[128] **aligned**;
> strncpy(read_t, sequence1->seq, length);
> strncpy(ref_t, sequence2->seq, length);
> bool proceedToAlignment = bit_vec_filter_sse1(read_t, ref_t, length, 1)
> 
> Could you advise if I have been using it the wrong way?
> Thank you in advance!
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/xhongyi/SHD_code/issues/1.

## 

# Hongyi Xin

Computer Science Department
Carnegie Mellon University
5000 Forbes ave.
Pittsburgh PA 15213
http://www.cs.cmu.edu/~hxin/

**Comment by mimitantono** [comment]
Hi Hongyi,

Thank you for replying. 
Please see below some example of pairs that passed q-gram filtering but does not pass alignment (max difference = 1):

1.
`gtcgctcctaccgattgaatacattggtgattgaattggataaagagatatcctcttaaatgatagcaaagcggtaagcatttgtaaactagattatttagaggaaggagaagtcgtaacaaggtttcc`
`gtcgctcctaccgattgaatacattggtgattgaattggataaagagatatcctcttaaatgatagcaaagcggtaaacatttgtaagctagattatttagaggaaggagaagtcgtaacaaggtttcc`

2.
`gtcgctcctaccgattgaatacattggtgattgaattggataaagagatatcctcttaaatgatagcaaagcggtaagcatttgtaaactagattatttagaggaaggagaagtcgtaacaaggtttcc`
`gtcgctcctaccgattgaatacattggtgattgaattggataaagagatatcctcttaaatgatagcaaagcggtaaaaatttgtaaactagattatttagaggaaggagaagtcgtaacaaggtttcc`

I will try replacing q-gram distance with SHD to see if it would improve the performance.
thanks!

Best regards

Mimi

**Comment by xhongyi** [comment]
Hi Mimi,

That makes sense.

The two strings you provided are awfully similar. SHD is a filter just like
the q-gram filter. It's job is to filter out drastically different string
pairs. It does not calculate the exact edit-distance however.

With small error thresholds, q-gram filtering provides a similar
performance and accuracy as SHD. With higher error thresholds, SHD should
have better accuracy than q-gram filtering.

Hongyi

On Tue, Feb 10, 2015 at 11:54 AM, mimitantono notifications@github.com
wrote:

> Hi Hongyi,
> 
> Thank you for replying.
> Please see below some example of pairs that passed q-gram filtering but
> does not pass alignment (max difference = 1):
> 
> 1.
> 
> gtcgctcctaccgattgaatacattggtgattgaattggataaagagatatcctcttaaatgatagcaaagcggtaagcatttgtaaactagattatttagaggaaggagaagtcgtaacaaggtttcc
> 
> gtcgctcctaccgattgaatacattggtgattgaattggataaagagatatcctcttaaatgatagcaaagcggtaaacatttgtaagctagattatttagaggaaggagaagtcgtaacaaggtttcc
> 
> 2.
> 
> gtcgctcctaccgattgaatacattggtgattgaattggataaagagatatcctcttaaatgatagcaaagcggtaagcatttgtaaactagattatttagaggaaggagaagtcgtaacaaggtttcc
> 
> gtcgctcctaccgattgaatacattggtgattgaattggataaagagatatcctcttaaatgatagcaaagcggtaaaaatttgtaaactagattatttagaggaaggagaagtcgtaacaaggtttcc
> 
> I will try replacing q-gram distance with SHD to see if it would improve
> the performance.
> thanks!
> 
> Best regards
> 
> Mimi
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/xhongyi/SHD_code/issues/1#issuecomment-73736332.

## 

# Hongyi Xin

Computer Science Department
Carnegie Mellon University
5000 Forbes ave.
Pittsburgh PA 15213
http://www.cs.cmu.edu/~hxin/

**Comment by mimitantono** [comment]
Thank you for your answers :) I'll discuss furthermore about this with my supervisor.
